-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE system_user
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login      VARCHAR NOT NULL,
    password   VARCHAR NOT NULL,
    name       VARCHAR NOT NULL,
    surname    VARCHAR NOT NULL,
    patronymic VARCHAR NOT NULL,
    birthday   DATE    NOT NULL,
    phone      VARCHAR NOT NULL,
    email      VARCHAR NOT NULL,
    gender     VARCHAR,

    CHECK (length(name) <= 20)
);

CREATE TABLE sport
(
    id   INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR NOT NULL
);

CREATE TABLE supervisor
(
    id             INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    system_user_id INT NOT NULL,

    FOREIGN KEY (system_user_id) REFERENCES system_user (id)
);

CREATE TABLE coach
(
    id             INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    system_user_id INT NOT NULL,

    FOREIGN KEY (system_user_id) REFERENCES system_user (id)
);

CREATE TABLE section
(
    id               INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sport_id         INT NOT NULL,
    supervisor_id    INT NOT NULL,
    max_in_group     INT NOT NULL,
    number_of_groups INT NOT NULL,

    FOREIGN KEY (sport_id) REFERENCES sport (id),
    FOREIGN KEY (supervisor_id) REFERENCES supervisor (id)
);

CREATE TABLE section_group
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    section_id INT NOT NULL,

    FOREIGN KEY (section_id) REFERENCES section (id)
);

CREATE TABLE user_group
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id  INT NOT NULL,
    group_id INT NOT NULL,

    FOREIGN KEY (user_id) REFERENCES system_user (id),
    FOREIGN KEY (group_id) REFERENCES section_group (id)
);

CREATE TABLE group_coach
(
    id       INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id  INT NOT NULL,
    coach_id INT NOT NULL,

    FOREIGN KEY (group_id) REFERENCES section_group (id),
    FOREIGN KEY (coach_id) REFERENCES coach (id)
);